name: SonicScape
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  onboarding: ^3.1.0
  get: ^4.6.6
  fl_chart: ^0.67.0
  intl: ^0.19.0
  http: ^1.2.2
  amplify_core: ^1.7.0
  amplify_auth_cognito: ^1.7.2
  amplify_flutter: ^1.7.0

  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1
  logger: ^2.2.0
  dio: ^5.4.3+1
  curl_logger_dio_interceptor: ^1.0.0
  flutter_downloader: ^1.11.7
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  mobile_scanner: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'   
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2


flutter:

  uses-material-design: true

  
  assets:
    - assets/images/

  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplayI.ttf
          weight: 400
        
  
  
  
